In [1]:
import numpy as np

In [13]:
W = np.random.rand(2,3)
X = np.random.rand(2)

In [14]:
print(X)
print(W)

[0.14151595 0.86649461]
[[0.94376869 0.23917395 0.08117416]
 [0.45532725 0.65249842 0.27863726]]


In [9]:
print(X)

[[0.49559244 0.79171236 0.37614583]
 [0.43509592 0.68014884 0.44714831]]
